**Standard Scaler**
  * transforms gaussian distributed data of differing
mean and standard deviations to standard gaussian
distributed data with mean of 0 and standard deviations 1
  * linear and logistic regression and 
 linear discriminant analysis and support vector machines, assumes all features are centered around zero and have same variance

*Parameters to control*
with_mean=False, with_std=False

[standardscaler](https://scikit-learn.org/stable/modules/preprocessing.html#preprocessing)

In [1]:
from sklearn.preprocessing import StandardScaler
import numpy as np

In [6]:
X_train = np.array([[ 1., -1.,  2.],
                     [ 2.,  0.,  0.],
                     [ 0.,  1., -1.]])
scaler = StandardScaler().fit(X_train)

In [7]:
scaler.mean_

array([1.        , 0.        , 0.33333333])

In [8]:
scaler.scale_

array([0.81649658, 0.81649658, 1.24721913])

In [9]:
X_scaled = scaler.transform(X_train)

In [10]:
X_scaled.mean(axis=0)

array([0., 0., 0.])

In [12]:
X_scaled.std(axis=0)

array([1., 1., 1.])

In [13]:
#manual step
# compute the mean value per feature on training set
mean_on_training = X_train.mean(axis=0)
#compute the std value per feature on training set
std_on_training = X_train.std(axis=0)

In [14]:
#subtract mean and scale by inverse standard deviation afterward
# mean=0, std=1
X_train_scaled = (X_train-mean_on_training)/std_on_training

In [15]:
X_train_scaled

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [16]:
X_train_scaled.mean(axis=0)

array([0., 0., 0.])

In [17]:
X_train_scaled.std(axis=0)

array([1., 1., 1.])