In [1]:
import tensorflow as tf
tf.__version__

'2.15.0'

**Constant**

In [10]:
tf_constant = tf.constant([2])
print (f"Shape of constant: {tf_constant.shape}")
print (f"Dimension of constant: {tf_constant.ndim}")
print (f"Type of constant: {tf_constant.dtype}")
print (f"Size of constant: {tf.size(tf_constant)}")

Shape of constant: (1,)
Dimension of constant: 1
Type of constant: <dtype: 'int32'>
Size of constant: 1


In [11]:
tf_constant = tf.constant([[2, 1, 3], [8, 4, 5]])
print (f"Shape of constant: {tf_constant.shape}")
print (f"Dimension of constant: {tf_constant.ndim}")
print (f"Type of constant: {tf_constant.dtype}")
print (f"Size of constant: {tf.size(tf_constant)}")

Shape of constant: (2, 3)
Dimension of constant: 2
Type of constant: <dtype: 'int32'>
Size of constant: 6


**Variable**

In [13]:
tf_variable = tf.Variable([2])
print (f"Shape of constant: {tf_variable.shape}")
print (f"Dimension of constant: {tf_variable.numpy().ndim}")
print (f"Type of constant: {tf_variable.dtype}")
print (f"Size of constant: {tf.size(tf_variable)}")

Shape of constant: (1,)
Dimension of constant: 1
Type of constant: <dtype: 'int32'>
Size of constant: 1


In [15]:
tf_variable = tf.Variable([[2, 1, 3], [8, 4, 5]])
print (f"Shape of constant: {tf_variable.shape}")
print (f"Dimension of constant: {tf_variable.numpy().ndim}")
print (f"Type of constant: {tf_variable.dtype}")
print (f"Size of constant: {tf.size(tf_variable)}")

Shape of constant: (2, 3)
Dimension of constant: 2
Type of constant: <dtype: 'int32'>
Size of constant: 6


In [20]:
tf_variable[1, 2].assign(20)
tf_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[ 2,  1,  3],
       [ 8,  4, 20]], dtype=int32)>

In [28]:
tf.Variable([[2, 1, 3], [8, 4, 5]], dtype=tf.float32)

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[2., 1., 3.],
       [8., 4., 5.]], dtype=float32)>

**ZEROS, ONES, ZEROS_LIKE, ONES_LIKE, EYS, FILL**

In [29]:
tf.zeros(shape=(3, 4), dtype=tf.float32)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [30]:
tf.ones(shape=(3, 4), dtype=tf.float32)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [31]:
tf.zeros_like(tf_variable)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [32]:
tf.ones_like(tf_variable)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [33]:
tf.eye(num_rows=3, num_columns=4)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]], dtype=float32)>

In [34]:
tf.fill(dims=(3, 4), value=2)

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]], dtype=int32)>

**Random**

In [35]:
tf.random.Generator.from_seed(42)
tf.random.normal(shape=(3, 4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 0.02705338, -0.31047344,  1.473036  ,  0.65940726],
       [-2.2578037 , -1.152767  , -0.6236002 ,  0.834756  ],
       [ 0.26912272,  0.03895365,  1.1246384 ,  1.3896104 ]],
      dtype=float32)>

In [36]:
tf.random.uniform(shape=(3, 4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0.20412767, 0.5849674 , 0.7949568 , 0.42401528],
       [0.19334316, 0.96687925, 0.6859462 , 0.6448792 ],
       [0.3203156 , 0.62359846, 0.8382907 , 0.37003672]], dtype=float32)>

**Slice**

In [39]:
var = tf.random.uniform(shape=(3, 4))
var, var[0:2, 0:2]

(<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
 array([[0.43034112, 0.67114913, 0.30797672, 0.5226424 ],
        [0.83283174, 0.28560722, 0.6346618 , 0.6259661 ],
        [0.24854755, 0.59215295, 0.4278481 , 0.90905094]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[0.43034112, 0.67114913],
        [0.83283174, 0.28560722]], dtype=float32)>)

In [40]:
var[0:2, ...]

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[0.43034112, 0.67114913, 0.30797672, 0.5226424 ],
       [0.83283174, 0.28560722, 0.6346618 , 0.6259661 ]], dtype=float32)>

**cast**

In [41]:
tf_variable.dtype

tf.float32

In [43]:
tf.cast(tf_variable, dtype=tf.int32)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 2, 10,  3],
       [ 8,  4,  5]], dtype=int32)>

In [44]:
tf.cast(tf_variable, dtype=tf.bool)

<tf.Tensor: shape=(2, 3), dtype=bool, numpy=
array([[ True,  True,  True],
       [ True,  True,  True]])>

**Math Operation**

In [45]:
tf.math.reduce_sum(tf_variable)

<tf.Tensor: shape=(), dtype=float32, numpy=32.0>

In [46]:
tf.math.reduce_mean(tf_variable)

<tf.Tensor: shape=(), dtype=float32, numpy=5.3333335>

In [47]:
tf.math.reduce_std(tf_variable)

<tf.Tensor: shape=(), dtype=float32, numpy=2.8087168>

In [49]:
tf.reduce_max(tf_variable)

<tf.Tensor: shape=(), dtype=float32, numpy=10.0>

In [50]:
tf.reduce_min(tf_variable)

<tf.Tensor: shape=(), dtype=float32, numpy=2.0>

In [54]:
tf_variable, tf.argmax(tf_variable, axis=1)

(<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
 array([[ 2., 10.,  3.],
        [ 8.,  4.,  5.]], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=int64, numpy=array([1, 0])>)

In [57]:
normal_dist = tf.random.normal(shape=(3, 4))
normal_dist

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 0.6851009 ,  0.9631424 ,  0.6427591 ,  0.4414306 ],
       [-1.7240741 , -0.6978763 ,  0.16039534,  1.7076049 ],
       [ 0.26735604,  1.7588849 , -0.46072307,  0.5835361 ]],
      dtype=float32)>

In [58]:
tf.abs(normal_dist)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0.6851009 , 0.9631424 , 0.6427591 , 0.4414306 ],
       [1.7240741 , 0.6978763 , 0.16039534, 1.7076049 ],
       [0.26735604, 1.7588849 , 0.46072307, 0.5835361 ]], dtype=float32)>

In [59]:
normal_dist1 = tf.random.normal(shape=(3, 4))
normal_dist2 = tf.random.normal(shape=(3, 4))
tf.add(normal_dist1, normal_dist2)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[-1.5390265 ,  3.248794  , -1.464366  , -1.7110083 ],
       [-0.79113805, -1.6979027 ,  1.0170016 , -0.7916398 ],
       [-0.48010483, -1.3972766 , -2.5596962 ,  0.98109627]],
      dtype=float32)>

In [60]:
tf.subtract(normal_dist1, normal_dist2)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[-0.9394949 , -1.6292257 ,  0.4706946 ,  1.314527  ],
       [ 0.3039172 , -0.10144287, -0.5507063 , -1.2356842 ],
       [ 0.9461309 , -0.6330044 , -0.28206837, -1.1139996 ]],
      dtype=float32)>

In [61]:
tf.multiply(normal_dist1, normal_dist2)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 0.37148792,  1.9750718 ,  0.48070353,  0.29989204],
       [ 0.13338342,  0.71814567,  0.1827537 , -0.22505546],
       [-0.16616572,  0.38792187,  1.6181207 , -0.06961133]],
      dtype=float32)>

In [62]:
tf.divide(normal_dist1, normal_dist2)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 4.1340966 ,  0.33201352,  0.51350915,  0.13104501],
       [ 0.44492808,  1.1270847 ,  0.2974376 , -4.5655885 ],
       [-0.32675245,  2.6564891 ,  1.247686  , -0.06343546]],
      dtype=float32)>

In [63]:
tf.equal(normal_dist1, normal_dist2)

<tf.Tensor: shape=(3, 4), dtype=bool, numpy=
array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])>

In [64]:
import tensorflow as tf

# Create a sample tensor
tensor = tf.constant([[1, 3, 2], [4, 0, 5]], dtype=tf.float32)
print(f'Original Tensor:\n{tensor}')

# Define the number of top elements to find
K = 2

# Find the top K elements and their indices along the last axis (default)
top_k_values, top_k_indices = tf.nn.top_k(tensor, k=K)
print(f'Top {K} values:\n{top_k_values}')
print(f'Indices of top {K} values:\n{top_k_indices}')

# Find the top K elements along axis 1 (rows)
top_k_values_axis_1, top_k_indices_axis_1 = tf.nn.top_k(tensor, k=K, sorted=True)
print(f'Top {K} values along axis 1:\n{top_k_values_axis_1}')
print(f'Indices of top {K} values along axis 1:\n{top_k_indices_axis_1}')


Original Tensor:
[[1. 3. 2.]
 [4. 0. 5.]]
Top 2 values:
[[3. 2.]
 [5. 4.]]
Indices of top 2 values:
[[1 2]
 [2 0]]
Top 2 values along axis 1:
[[3. 2.]
 [5. 4.]]
Indices of top 2 values along axis 1:
[[1 2]
 [2 0]]


In [65]:
tf.sigmoid(tensor)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.7310586 , 0.95257413, 0.8807971 ],
       [0.98201376, 0.5       , 0.9933072 ]], dtype=float32)>

**Matrix**

In [74]:
a = tf.constant([[1, 2, 3], [4, 5, 6]], dtype=tf.float32)
b = tf.constant([[1, 2, 3], [4, 5, 6]], dtype=tf.float32)
a.shape, tf.transpose(b).shape

(TensorShape([2, 3]), TensorShape([3, 2]))

In [75]:
tf.matmul(a, tf.transpose(b))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[14., 32.],
       [32., 77.]], dtype=float32)>

In [84]:
a, tf.linalg.band_part(a, 0, 0)

(<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
 array([[1., 2., 3.],
        [4., 5., 6.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 3), dtype=float32, numpy=
 array([[1., 0., 0.],
        [0., 5., 0.]], dtype=float32)>)

In [85]:
a, tf.linalg.band_part(a, 0, -1)

(<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
 array([[1., 2., 3.],
        [4., 5., 6.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 3), dtype=float32, numpy=
 array([[1., 2., 3.],
        [0., 5., 6.]], dtype=float32)>)

In [87]:
a = tf.constant([[1, 2], [4, 5]], dtype=tf.float32)
a, tf.linalg.det(a)

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[1., 2.],
        [4., 5.]], dtype=float32)>,
 <tf.Tensor: shape=(), dtype=float32, numpy=-3.0>)

In [89]:
a = tf.constant([[1, 2], [4, 5]], dtype=tf.float32)
a, tf.rank(a)

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[1., 2.],
        [4., 5.]], dtype=float32)>,
 <tf.Tensor: shape=(), dtype=int32, numpy=2>)

In [90]:
a = tf.constant([[1, 2], [4, 5]], dtype=tf.float32)
a, tf.linalg.inv(a)

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[1., 2.],
        [4., 5.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[-1.6666667 ,  0.6666667 ],
        [ 1.3333334 , -0.33333334]], dtype=float32)>)

In [92]:
a = tf.constant([[1, 2, 3], [4, 5, 6]], dtype=tf.float32)
b = tf.constant([[1, 2, 3], [4, 5, 6]], dtype=tf.float32)
tf.linalg.einsum('ij,jk->ik', a, tf.transpose(b))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[14., 32.],
       [32., 77.]], dtype=float32)>

In [94]:
tf.linalg.einsum('ij,jk->ij', a, tf.transpose(b))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 5., 14., 27.],
       [20., 35., 54.]], dtype=float32)>

In [76]:
tf.expand_dims(a, axis=0)

<tf.Tensor: shape=(1, 2, 3), dtype=float32, numpy=
array([[[1., 2., 3.],
        [4., 5., 6.]]], dtype=float32)>

In [81]:
tf.squeeze(tf.expand_dims(a, axis=0))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [82]:
tf.reshape(a, shape=(3, 2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float32)>

In [6]:
# Create sample tensors
tensor1 = tf.constant([[1, 2], [3, 4]], dtype=tf.float32)
tensor2 = tf.constant([[5, 6], [7, 8]], dtype=tf.float32)

# Concatenate tensors along the first axis (rows)
concatenated_tensor = tf.concat([tensor1, tensor2], axis=0)
concatenated_tensor1 = tf.concat([tensor1, tensor2], axis=1)
print(f'Tensor 1:\n{tensor1.numpy()}')
print(f'Tensor 2:\n{tensor2.numpy()}')
print(f'Concatenated Tensor along axis 0 (rows):\n{concatenated_tensor.numpy()}')
print(f'Concatenated Tensor along axis 0 (rows):\n{concatenated_tensor1.numpy()}')

Tensor 1:
[[1. 2.]
 [3. 4.]]
Tensor 2:
[[5. 6.]
 [7. 8.]]
Concatenated Tensor along axis 0 (rows):
[[1. 2.]
 [3. 4.]
 [5. 6.]
 [7. 8.]]
Concatenated Tensor along axis 0 (rows):
[[1. 2. 5. 6.]
 [3. 4. 7. 8.]]


In [8]:
import tensorflow as tf

# Create sample tensors
tensor1 = tf.constant([1, 2, 3], dtype=tf.float32)
tensor2 = tf.constant([4, 5, 6], dtype=tf.float32)
tensor3 = tf.constant([7, 8, 9], dtype=tf.float32)

# Stack tensors along a new axis (default axis 0)
stacked_tensor = tf.stack([tensor1, tensor2, tensor3])
print(f'Tensor 1:\n{tensor1.numpy()}')
print(f'Tensor 2:\n{tensor2.numpy()}')
print(f'Tensor 3:\n{tensor3.numpy()}')
print(f'Stacked Tensor along axis 0:\n{stacked_tensor.numpy()}')
print(f'Stacked Tensor shape: {stacked_tensor.shape}')

# Stack tensors along a new axis 1
stacked_tensor_axis1 = tf.stack([tensor1, tensor2, tensor3], axis=1)
print(f'Stacked Tensor along axis 1:\n{stacked_tensor_axis1.numpy()}')
print(f'Stacked Tensor shape: {stacked_tensor_axis1.shape}')


Tensor 1:
[1. 2. 3.]
Tensor 2:
[4. 5. 6.]
Tensor 3:
[7. 8. 9.]
Stacked Tensor along axis 0:
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Stacked Tensor shape: (3, 3)
Stacked Tensor along axis 1:
[[1. 4. 7.]
 [2. 5. 8.]
 [3. 6. 9.]]
Stacked Tensor shape: (3, 3)


In [9]:
import tensorflow as tf

# Create a sample tensor
tensor = tf.constant([[1, 2, 3], [4, 5, 6]], dtype=tf.float32)

# Define padding
# Each element in paddings is [pad_before, pad_after]
paddings = [[1, 1], [2, 2]]

# Pad the tensor
padded_tensor = tf.pad(tensor, paddings)
print(f'Original Tensor:\n{tensor.numpy()}')
print(f'Padded Tensor:\n{padded_tensor.numpy()}')


Original Tensor:
[[1. 2. 3.]
 [4. 5. 6.]]
Padded Tensor:
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 2. 3. 0. 0.]
 [0. 0. 4. 5. 6. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [10]:
import tensorflow as tf

# Create a sample tensor
tensor = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=tf.float32)

# Define indices
indices = [0, 2]

# Gather slices from tensor along axis 0
gathered_tensor = tf.gather(tensor, indices, axis=0)
print(f'Original Tensor:\n{tensor.numpy()}')
print(f'Indices: {indices}')
print(f'Gathered Tensor along axis 0:\n{gathered_tensor.numpy()}')

# Gather slices from tensor along axis 1
gathered_tensor_axis1 = tf.gather(tensor, indices, axis=1)
print(f'Gathered Tensor along axis 1:\n{gathered_tensor_axis1.numpy()}')


Original Tensor:
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Indices: [0, 2]
Gathered Tensor along axis 0:
[[1. 2. 3.]
 [7. 8. 9.]]
Gathered Tensor along axis 1:
[[1. 3.]
 [4. 6.]
 [7. 9.]]


In [12]:
# Create a sample tensor
tensor = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=tf.float32)

# Gather specific elements (e.g., diagonal elements)
gathered_elements = tf.gather_nd(tensor, [[0, 0], [1, 1], [2, 2]])
print(f'Original Tensor:\n{tensor.numpy()}')
print(f'Gathered Elements:\n{gathered_elements.numpy()}')


Original Tensor:
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Gathered Elements:
[1. 5. 9.]


In [13]:
# Create a ragged tensor representing variable-length sequences
sequences = tf.ragged.constant([
    [7, 8, 9],
    [10, 11],
    [12, 13, 14, 15],
    [16]
])
print(f'Sequences:\n{sequences}')


Sequences:
<tf.RaggedTensor [[7, 8, 9], [10, 11], [12, 13, 14, 15], [16]]>


In [14]:
# Define the indices of the non-zero elements
indices = [[0, 0], [1, 2], [2, 3]]

# Define the values at the specified indices
values = [1, 2, 3]

# Define the shape of the dense tensor
dense_shape = [3, 4]

# Create the sparse tensor
sparse_tensor = tf.SparseTensor(indices=indices, values=values, dense_shape=dense_shape)
print(f'Sparse Tensor:\n{tf.sparse.to_dense(sparse_tensor)}')


Sparse Tensor:
[[1 0 0 0]
 [0 0 2 0]
 [0 0 0 3]]


In [15]:
import tensorflow as tf

# Create a string tensor
string_tensor = tf.constant(["TensorFlow", "String", "Tensors"])
print(f'String Tensor: {string_tensor}')

# Convert strings to lowercase
lowercase_tensor = tf.strings.lower(string_tensor)
print(f'Lowercase Tensor: {lowercase_tensor}')

# Split strings on a delimiter (e.g., space)
split_tensor = tf.strings.split(["Hello World", "TensorFlow Strings"])
print(f'Split Tensor: {split_tensor}')

# Join strings with a separator
joined_tensor = tf.strings.join(["Hello", "World"], separator=" ")
print(f'Joined Tensor: {joined_tensor}')

# Extract substrings
substring_tensor = tf.strings.substr(string_tensor, pos=0, len=6)
print(f'Substring Tensor: {substring_tensor}')


String Tensor: [b'TensorFlow' b'String' b'Tensors']
Lowercase Tensor: [b'tensorflow' b'string' b'tensors']
Split Tensor: <tf.RaggedTensor [[b'Hello', b'World'],
 [b'TensorFlow', b'Strings']]>
Joined Tensor: b'Hello World'
Substring Tensor: [b'Tensor' b'String' b'Tensor']
